FROM php:8.3-apache

# Устанавливаем расширения для работы с MySQL
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Включаем mod_rewrite
RUN a2enmod rewrite

# Настраиваем DocumentRoot на public
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

COPY . /var/www/html